pipeline {

    agent any

    stages {

        stage('Repository Cloned Successfully') {

            steps {

                bat 'echo Repository downloaded successfully'

            }

        }

        stage('CI/CD Pipeline Started') {

            steps {

                bat 'echo Jenkins pipeline execution successful'

            }

        }

        stage('Docker Build Trigger') {

            steps {

                bat 'echo Docker build stage triggered'

            }

        }

    }

}
